//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.22 at 02:08:40 PM CEST 
//


package oasis.names.tc.entity.xmlns.xml.catalog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.entity.xmlns.xml.catalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupPublic_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "public");
    private final static QName _GroupUri_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "uri");
    private final static QName _GroupRewriteSystem_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "rewriteSystem");
    private final static QName _GroupDelegateSystem_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "delegateSystem");
    private final static QName _GroupNextCatalog_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "nextCatalog");
    private final static QName _GroupRewriteURI_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "rewriteURI");
    private final static QName _GroupDelegateURI_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "delegateURI");
    private final static QName _GroupDelegatePublic_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "delegatePublic");
    private final static QName _GroupSystem_QNAME = new QName("urn:oasis:names:tc:entity:xmlns:xml:catalog", "system");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.entity.xmlns.xml.catalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NextCatalog }
     * 
     */
    public NextCatalog createNextCatalog() {
        return new NextCatalog();
    }

    /**
     * Create an instance of {@link Uri }
     * 
     */
    public Uri createUri() {
        return new Uri();
    }

    /**
     * Create an instance of {@link RewriteURI }
     * 
     */
    public RewriteURI createRewriteURI() {
        return new RewriteURI();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link Public }
     * 
     */
    public Public createPublic() {
        return new Public();
    }

    /**
     * Create an instance of {@link DelegateURI }
     * 
     */
    public DelegateURI createDelegateURI() {
        return new DelegateURI();
    }

    /**
     * Create an instance of {@link DelegatePublic }
     * 
     */
    public DelegatePublic createDelegatePublic() {
        return new DelegatePublic();
    }

    /**
     * Create an instance of {@link System }
     * 
     */
    public System createSystem() {
        return new System();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link RewriteSystem }
     * 
     */
    public RewriteSystem createRewriteSystem() {
        return new RewriteSystem();
    }

    /**
     * Create an instance of {@link DelegateSystem }
     * 
     */
    public DelegateSystem createDelegateSystem() {
        return new DelegateSystem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Public }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "public", scope = Group.class)
    public JAXBElement<Public> createGroupPublic(Public value) {
        return new JAXBElement<Public>(_GroupPublic_QNAME, Public.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Uri }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "uri", scope = Group.class)
    public JAXBElement<Uri> createGroupUri(Uri value) {
        return new JAXBElement<Uri>(_GroupUri_QNAME, Uri.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RewriteSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "rewriteSystem", scope = Group.class)
    public JAXBElement<RewriteSystem> createGroupRewriteSystem(RewriteSystem value) {
        return new JAXBElement<RewriteSystem>(_GroupRewriteSystem_QNAME, RewriteSystem.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegateSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "delegateSystem", scope = Group.class)
    public JAXBElement<DelegateSystem> createGroupDelegateSystem(DelegateSystem value) {
        return new JAXBElement<DelegateSystem>(_GroupDelegateSystem_QNAME, DelegateSystem.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NextCatalog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "nextCatalog", scope = Group.class)
    public JAXBElement<NextCatalog> createGroupNextCatalog(NextCatalog value) {
        return new JAXBElement<NextCatalog>(_GroupNextCatalog_QNAME, NextCatalog.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RewriteURI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "rewriteURI", scope = Group.class)
    public JAXBElement<RewriteURI> createGroupRewriteURI(RewriteURI value) {
        return new JAXBElement<RewriteURI>(_GroupRewriteURI_QNAME, RewriteURI.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegateURI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "delegateURI", scope = Group.class)
    public JAXBElement<DelegateURI> createGroupDelegateURI(DelegateURI value) {
        return new JAXBElement<DelegateURI>(_GroupDelegateURI_QNAME, DelegateURI.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegatePublic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "delegatePublic", scope = Group.class)
    public JAXBElement<DelegatePublic> createGroupDelegatePublic(DelegatePublic value) {
        return new JAXBElement<DelegatePublic>(_GroupDelegatePublic_QNAME, DelegatePublic.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link System }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", name = "system", scope = Group.class)
    public JAXBElement<System> createGroupSystem(System value) {
        return new JAXBElement<System>(_GroupSystem_QNAME, System.class, Group.class, value);
    }

}
